server:
  port: 9092



spring:
    profiles: local
#  redis:
#    host: localhost
#    port: 6379
#    database: 2
#    pool:
#      max-active: 50
#      max-idle: 10
#      max-wait: 3000

    datasource:
        url: jdbc:mysql://localhost:3306/activiti6ui?characterEncoding=utf8&useSSL=true
        username: root
        password: zrh981025
        driverClassName: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
    activiti:
      database-schema-update: true
      check-process-definitions: false
activiti:
      database-schema-update: true
      check-process-definitions: false
      
mybatis:
  typeAliasesPackage: com.example.demo.entity
  mapperLocations: classpath:mapper/*.xml
